version: '3'
services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - mongodb_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mqtt_broker
      - mongodb
      - redis
    networks:
      - fastapi_network

networks:
  mqtt_network:
    driver: bridge

  mongodb_network:
    driver: bridge

  redis_network:
    driver: bridge

  fastapi_network:
    driver: bridge
